apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodbvolume.pvName }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.mongodbvolume.storage }}
  accessModes: {{ .Values.mongodbvolume.pvAccessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.mongodbvolume.pvReclaimPolicy }}
  storageClassName: {{ .Values.mongodbvolume.storageClassName }}
  local:
    path: {{ .Values.mongodbvolume.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.mongodbvolume.nodeSelectorKey }}
          operator: In
          values:
          - "{{ .Values.volume.nodeSelectorValue }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodbvolume.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ .Values.mongodbvolume.pvAccessModes }}
  storageClassName: {{ .Values.mongodbvolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongodbvolume.storage }}
